concertcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('venues/', views.venues_index, name='index'),
  path('venues/<int:venue_id>/', views.venues_detail, name='detail'),
  path('venues/create/', views.VenueCreate.as_view(), name='venues_create'),
  path('venues/<int:pk>/update/', views.VenueUpdate.as_view(), name='venues_update'),
  path('venues/<int:pk>/delete/', views.VenueDelete.as_view(), name='venues_delete'),
  path('venues/<int:venue_id>/new_concert/', views.new_concert, name='new_concert'),
  path('concerts/<int:concert_id>/', views.concerts_detail, name='concert_detail'),
  path('artists/', views.artists_index, name='artists_index'),
  path('artists/create/', views.ArtistCreate.as_view(), name='artist_create'),
  path('artists/<int:pk>/delete/', views.ArtistDelete.as_view(), name='artists_delete'),
  path('cats/<int:concert_id>/unassoc_artist/<int:artist_id>/', views.unassoc_artist, name='unassoc_artist')
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Artist(models.Model):
  name = models.CharField(max_length=100)

class Venue(models.Model):
  name = models.CharField(max_length=100)
  location = models.CharField(max_length=100)

  def get_absolute_url(self):
    return reverse('detail', kwargs={'venue_id': self.id})

class Concert(models.Model):
  artists = models.ManyToManyField(Artist)
  venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
  date = models.DateField()
  best_songs = models.TextField(max_length=250)

  class Meta:
    ordering = ['-date']
  
  def get_absolute_url(self):
    return reverse('detail', kwargs={'concert_id': self.id})
   

main_app/forms.py
from django.forms import ModelForm
from .models import Concert

class ConcertForm(ModelForm):
    class Meta:
        model = Concert
        fields = ['date', 'best_songs']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, DeleteView
from .models import Venue, Concert, Artist
from .forms import ConcertForm

# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def venues_index(request):
  venues = Venue.objects.all()
  return render(request, 'venues/index.html', { 'venues': venues })

def venues_detail(request, venue_id):
  venue = Venue.objects.get(id=venue_id)
  return render(request, 'venues/detail.html', { 'venue': venue })

def new_concert(request, venue_id):
  venue_id = venue_id
  concert_form = ConcertForm()
  artists = Artist.objects.all()
  if request.method == 'POST':
    concert_artists = request.POST.getlist('artists')
    for i in range(0, len(concert_artists)):
        concert_artists[i] = int(concert_artists[i])
    venue = Venue.objects.get(id=venue_id)
    form = Concert.objects.create(venue=venue, date=request.POST['date'], best_songs=request.POST['best_songs'])
    form.artists.set(concert_artists)
    new_concert = form.save()
    return redirect('concert_detail', concert_id=form.id)
  return render(request, 'concerts/new.html', { 'artists': artists, 'venue_id': venue_id, 'concert_form': concert_form })

def concerts_detail(request, concert_id):
  concert = Concert.objects.get(id=concert_id)
  concert_form = ConcertForm()
  artists = concert.artists.all()
  venue = concert.venue
  print(artists)
  return render(request, 'concerts/detail.html', { 'concert': concert, 'concert_form': concert_form, 'artists': artists, 'venue': venue })

class VenueCreate(CreateView):
  model = Venue
  fields = '__all__'

class VenueUpdate(UpdateView):
  model = Venue
  fields = '__all__'

class VenueDelete(DeleteView):
  model = Venue
  success_url = '/venues/'

def artists_index(request):
  artists = Artist.objects.all()
  return render(request, 'artists/index.html', { 'artists': artists })

class ArtistCreate(CreateView):
  model = Artist
  fields = '__all__'
  success_url = '/artists/'

class ArtistDelete(DeleteView):
  model = Artist
  success_url = '/artists/'

def unassoc_artist(request, concert_id, artist_id):
  Concert.objects.get(id=concert_id).artists.remove(artist_id)
  return redirect('concert_detail', concert_id=concert_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Concert Collector</h1>
<hr />

{% endblock %}

main_app/templates/artists/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Artist List</h1>

{% for artist in artists %}
  <div class="card">
    <div class="card-content">
        <table>
           <tr>
               <td>{{ artist.name }}</td>
               <td><a href="{% url 'artists_delete' artist.id %}">Delete</a></td>
           </tr> 
        </table>
    </div>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Concert Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Concert Collector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'index' %}">View Venues</a></li>
                    <li><a href="{% url 'venues_create' %}">Add Venue</a></li>
                    <li><a href="{% url 'artists_index' %}">View Artists</a></li>
                    <li><a href="{% url 'artist_create' %}">Add Artist</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
  	<footer class="page-footer">
       <div class="right">All Rights Reserved, &copy; 2019 Concert Collector &nbsp;</div>
    </footer>
</body>
</html>

main_app/templates/concerts/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Concert Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ concert.date }}</span>
        <p><a href="{% url 'detail' venue.id %}">{{ venue.name }}</a></p>
        {% for artist in artists %}
        <table>
            <tr>
                <td>{{ artist.name }}</td>
                <td>
                    <form action="{% url 'unassoc_artist' concert.id artist.id %}" method="post">
                        {% csrf_token %}
                      <button type="submit">Remove</button>
                    </form>
                </td>
            </tr>
        </table> 
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<hr>

{% endblock %}

main_app/templates/concerts/new.html
{% extends 'base.html' %}
{% block content %}

<h1>New Concert</h1>

<div class="col s6">
    
    <form action="" method="post">
     {% csrf_token %}
        <h5>Who performed?</h5>
          {% for artist in artists.all %}
          <p>
              <label>
                  <input type="checkbox" name="artists" value="{{ artist.id }}">
                  <span>{{ artist.name }}</span>
              </label>
          </p>
          {% endfor %}
          {{ concert_form.as_p }}
        <button type="submit" class="btn">Add</button>
    </form>

</div>

  <script>

    var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
  
  </script>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/artist_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn">
  <a href="{% url 'artists_index' %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/artist_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
<h1>Add Artist</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Add Artist" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/venue_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn">
  <a href="{% url 'detail' venue.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/venue_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
<h1>Add Venue</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table> 
        {{ form.as_table }}
    </table>
    <input type="submit" value="Add Venue" class="btn">
</form>

{% endblock %}

main_app/templates/venues/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Venue Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ venue.name }}</span>
        <p>{{ venue.location }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'venues_update' venue.id %}">Edit</a>
        <a href="{% url 'venues_delete' venue.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <h6>Concerts attended</h6>
    <table class="striped">
      <thead>
        <tr><th>Date</th></tr>
      </thead>
      <tbody>
        {% for concert in venue.concert_set.all %}
          <tr>
            <td><a href="{% url 'concert_detail' concert.id %}">{{ concert.date }}</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="card-action">
      <a href="{% url 'new_concert' venue.id %}">Add a Concert</a>
    </div>
  </div>
</div>

{% endblock %}

main_app/templates/venues/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Venue List</h1>

{% for venue in venues %}
<a href="{% url 'detail' venue.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ venue.name }}</span>
      <p>{{ venue.location }}</p>
    </div>
  </div>
</a>
{% endfor %}

{% endblock %}